spring:
  http:
    clients:
      connect-timeout: 15s
      read-timeout: 15s
azure:
  ai-search:
    instance: https://pilot-plus-ai-search-dev.search.windows.net
    apiKey: ${AZURE_AI_SEARCH_API_KEY:}
    isVectorSearchEnabled: ${IS_VECTOR_SEARCH_ENABLED:false}
dify:
  apiKey: ${DIFY_API_KEY:}